-- Role: books

-- DROP ROLE books;

CREATE ROLE books LOGIN
  ENCRYPTED PASSWORD 'md5137f9ee2654c6e847fc2b921a07f8ff4'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;


-- Database: books

-- DROP DATABASE books;

CREATE DATABASE books
  WITH OWNER = books
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'en_US.UTF-8'
       LC_CTYPE = 'en_US.UTF-8'
       CONNECTION LIMIT = -1;


-- DROP TABLE BOOK;

CREATE TABLE BOOK(
 ID INTEGER PRIMARY KEY,
 ISBN VARCHAR,
 NAME VARCHAR
);

ALTER TABLE BOOK
  OWNER TO BOOKS;